---
title: "Replication 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Install Required Packages
rm(list = ls())

library(ri)
library(RItools)
library(car)
library(xtable)
library(effects)
library(RColorBrewer)
library(gt)
library(knitr)
library(dplyr)
library(data.table)


# Set for non-scientific notaion output
options(scipen = 999)

# Load data

dat.all = read.csv('./csvData/pnas_data.csv')
dat.t1 = read.csv('./csvData/t1_data.csv')
dat.all.prime = read.csv('./csvData/prime_data.csv')

# Data loading for faces graphic
conf.dat = read.csv('./csvData/confederate_face_data.csv')
hisp.dat = read.csv('./csvData/hispanic_face_data.csv')
white.dat = read.csv('./csvData/white_face_data.csv')

```

```{r table1}


```

```{r table2, echo = FALSE, results = 'asis'}

# Table 2

# BALANCE CHECK: Check to see whether there are confounding varaibles 
#   relating to which station is being sampled
# xBalance function calculates std mean dif. along each covariate, given
#   covariates, a treatment variable and a stratifying factor (factor which
#   can seperate data into subgroups)
# Report indicates which results we would like to see
# Strata refers to the set of the population which is being sampled. In this 
#   case, it is the list of train stations

out.balance.test = xBalance(fmla = treatment ~ liberal+republican+obama.disapprove+ride.everyday+voted.2010+romney.voter+Hispanics.x+age+residency.new+hispanic.new+college+income.new+male+white, data = dat.all, report = c("std.diffs","z.scores","adj.means","chisquare.test"), strata = factor(dat.all$station))

# Convert the output into a dataframe and select the appropriate columns

table2Data <- as.data.frame(out.balance.test) %>% 
  select(results.treatment.0.strat, 
         results.treatment.1.strat,
         results.std.diff.strat,
         results.z.strat)

# Use the data table package to turn the row titles into a colunn

setDT(table2Data, keep.rownames = TRUE)[]

# Use colnames function to rename the columns

colnames(table2Data) <- c("Condition", "Control", "Treatment", "Standard difference", "Z score")

# Rename the Condition column to appropriate values

table2Data$Condition = c("Liberal", 
                         "Republican", 
                         "Obama Disapprove", 
                         "Ride MBTA every day",
                         "Voted 2010",
                         "Romney voter",
                         "Hispanic threat",
                         "Age",
                         "Residency Year",
                         "Hispanic",
                         "College",
                         "Income",
                         "Male",
                         "White")

# Use gt to create the table

table2 <- gt(data = table2Data)

# Round the table values to 2 values

fmt_number(data = table2, columns = c("Control", "Treatment", "Standard difference", "Z score"), decimals = 2)

```
